apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onepagewebsite-ing
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: onepagewebsite.{{ .Values.dns.name }}
      http:
        paths:
          - backend:
              service:
                name: onepagewebsite-svc
                port:
                  name: http
            path: /
            pathType: Prefix