apiVersion: v1
kind: Service
metadata:
  name: onepagewebsite-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: onepagewebsite-ui
  type: ClusterIP