
name: Build and deploy an app to AKS

on: workflow_dispatch

env:
  AZURE_CONTAINER_REGISTRY: "azurecnapp"
  CONTAINER_NAME: "cloudvignanaonepagewebsite"
  RESOURCE_GROUP: "k8s"
  CLUSTER_NAME: "cna-platform-Prod"
  DEPLOYMENT_MANIFEST_PATH: "deployment"
  IMAGE_TAG: "latest" # default github.sha

jobs:
  code-quality:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: SonarCloud Scan 
        uses: SonarSource/sonarcloud-github-action@v1.7
        env:          
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          
      
  build-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with  Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      # Builds and pushes an image up to  Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ IMAGE_TAG }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

